apiVersion: v2
name: kafka-helm
version: 0.1.0
description: A Helm chart to deploy Kafka cluster with Strimzi

dependencies:
  - name: strimzi-kafka-operator
    version: 0.41.0
    repository: https://strimzi.io/charts/
