apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
  namespace: consumer-ns
spec:
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      port: 9092      # Kafka consumer will connect to the broker at this port
      targetPort: 9092
  clusterIP: None
