apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: {{ .Release.Namespace }}
spec:
  kafka:
    replicas: {{ .Values.kafka.replicas }}
    version: {{ .Values.kafka.version }}
    listeners:
      {{- range .Values.kafka.listeners }}
      - name: {{ .name }}
        port: {{ .port }}
        type: {{ .type }}
        tls: {{ .tls }}
      {{- end }}
    config:
      {{- toYaml .Values.kafka.config | nindent 8 }}
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      class: {{ .Values.kafka.storage.class }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.size }}
      class: {{ .Values.zookeeper.storage.class }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
