apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.brokers }}
    listeners:
    {{- range .Values.kafka.listeners }}
      - name: {{ .name }}
        port: {{ .port }}
        type: {{ .type }}
        tls: {{ .tls }}
    {{- end }}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: {{ .Values.kafka.version }}
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      class: {{ .Values.kafka.storage.class }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.size }}
      class: {{ .Values.zookeeper.storage.class }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
