apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.topic.name }}
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: {{ .Values.topic.partitions }}
  replicas: {{ .Values.topic.replicas }}
  config:
    retention.ms: {{ .Values.topic.retention.ms }}
    segment.bytes: {{ .Values.topic.config.segment.bytes }}
    cleanup.policy: {{ .Values.topic.config.cleanup.policy }}
