apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  namespace: producer-ns
spec:
  selector:
    app: kafka-producer 
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  clusterIP: None
