apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: "3.8.1"
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: {{ .Values.kafka.port }}
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.config.default.replication.factor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.default.replication.factor }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.default.replication.factor }}
      log.message.format.version: "3.6"
    storage:
      type: ephemeral
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
