apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.topic.name }}
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: {{ .Values.topic.partitions }}
  replicas: {{ .Values.topic.replicas }}
  topicName: {{ .Values.topic.name }}
